### ISSUE TITLE
server.bootstrap is in default config file but never used in netauthd

### ISSUE THREAD

**Issue by CyrusJavan** [netauth/docs#3]
In src/setup/setup.md there is default config file that includes a field for server.bootstrap.
```
[server]
  bind = "localhost"
  bootstrap = ""
  port = 1729
```
However netauthd never reads this field from the config file. Instead the only way to set server.bootstrap is via command line flags. This field should either be removed from the default config or the value from the config file should actually be used in netauthd.

**Comment by the-maldridge** [comment]
This is an idiosyncracy of how viper and pflag interact.  The default value of an empty string which is set in pflag is taken as a value that is then used in viper when defaults are written out.  It should be sufficient to just drop the value from the documentation.
